<a href="https://colab.research.google.com/github/AnshCoderRepo/Exercise1/blob/main/Exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
train_df=pd.read_csv('train_ctrUa4K.csv')
# the below piece of code tells about the total number of missing values in each column
print(train_df.isnull().sum())

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64


In [ ]:
#to find the total number of  missing values from entire data set use the below code
print(train_df.isnull().sum().sum())

149


In [ ]:
# droping row from the data set if it has missing values
df=train_df.dropna(axis=0)
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [ ]:
#code to drop the entire column if it has missing values
#df=train_df.drop(['column_name'], axis=1)
df=train_df.drop(['Credit_History'], axis=1)
print(df.isnull().sum())

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Property_Area         0
Loan_Status           0
dtype: int64


In [ ]:
# Imputing the missing values Replacing the missing values with zero

train_df['Dependents'] =train_df['Dependents'].fillna(0)
train_df['Dependents'].isnull().sum()


0

In [ ]:
#impute mean value in place of missing values
train_df['LoanAmount']= train_df['LoanAmount'].fillna(train_df['LoanAmount'].mean())
print(train_df.isnull().sum())

Loan_ID               0
Gender               13
Married               3
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64


In [ ]:
# impute missing value with the mode of that column

train_df['LoanAmount']=train_df['LoanAmount'].fillna(train_df['LoanAmount'].mode())
print(train_df.isnull().sum())

Loan_ID               0
Gender               13
Married               3
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64


In [ ]:
# impute missing value with the mode of that column of string-> mode()[0]-> gives the first most frequent element
train_df['Gender'] =train_df['Gender'].fillna(train_df['Gender'].mode()[0])
train_df['Married']=train_df['Married'].fillna(train_df['Married'].mode()[0])
print(train_df.isnull().sum())

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64


In [ ]:
# impute missing value with the median of that column use this in case of outliers
train_df['LoanAmount']=train_df['LoanAmount'].fillna(train_df['LoanAmount'].median())
print(train_df.isnull().sum())


Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64


In [ ]:
#impute missing string values in the dataset -> unknown is the value which is  to be replaced
train_df.fillna(value={'Self_Employed':'Unknown'},inplace=True)#inplace=true means to make chnages in the current data set instead of return a new one
print(train_df.isnull().sum())

Loan_ID               0
Gender                0
Married               0
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64


In [ ]:
# alternative to impute string missing values
Self_Employed=train_df.select_dtypes(include=['object']).columns
train_df['Self_Employed']=train_df['Self_Employed'].fillna('unknown')
print(train_df['Self_Employed'].isnull().sum())

0


In [ ]:
# impute data using forward fill method
import pandas as pd
import numpy as np
test =pd.Series(range(6))
test.loc[2:4]=np.nan
test

0    0.0
1    1.0
2    NaN
3    NaN
4    NaN
5    5.0
dtype: float64

In [ ]:
# implementing forward fill
test.fillna(method='ffill')


0    0.0
1    1.0
2    1.0
3    1.0
4    1.0
5    5.0
dtype: float64

In [ ]:
# implementing vlues using backward fill

test.fillna(method='bfill')

0    0.0
1    1.0
2    5.0
3    5.0
4    5.0
5    5.0
dtype: float64

In [ ]:

# imputing values using interpolation method of filling up the missing values
#-> Three Method -- Linaer,quadratic,polynomail
test.interpolate(method='linear')

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
dtype: float64

In [ ]:
# impute missing values fpr categorical features
# two methods -> 1> IMpute most frequent value
import pandas as pd
import numpy as np
X=pd.DataFrame({'Shape':['Square','Square','Oval','circle',np.nan]})
X

Shape
0  Square
1  Square
2    Oval
3  circle
4     NaN

In [ ]:
#We will use ‘SimpleImputer’ in this case, and as this is a non-numeric column, we can’t use
#mean or median, but we can use the most frequent value and constant.
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(strategy='most_frequent')
imputer.fit_transform(X)

array([['Square'],
       ['Square'],
       ['Oval'],
       ['circle'],
       ['Square']], dtype=object)

In [ ]:
# 2> Impute the missing value"Missing"

imputer= SimpleImputer(strategy='constant', fill_value='missing')
imputer.fit_transform(X)

array([['Square'],
       ['Square'],
       ['Oval'],
       ['circle'],
       ['missing']], dtype=object)

In [ ]:
# impute missing value using scikit learn
# predict the observed value of a variable based
#on another variable which is known as regression imputation.

In [ ]:
#Univariate Approach
#-> only a single feature is taken into consideration. SimpleImputer and replace the missing values with
# mean, mode, median, or some constant value

import numpy as np
from  sklearn.impute  import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
imp.fit([[1,2],[np.nan,3],[7,6]])


SimpleImputer()

In [ ]:
X=[[np.nan,2],[6,np.nan],[7,6]]
print(imp.transform(X))

[[4.         2.        ]
 [6.         3.66666667]
 [7.         6.        ]]


In [ ]:
# Multivariate Approach
#-> more than one feature is taken into consideration
# -> There are two ways to impute missing values considering the multivariate approach. Using KNNImputer or IterativeImputer classes


import pandas as pd
df= pd.read_csv('titanic3.csv',nrows=6)
cols=['sibsp','fare','age']
X=df[cols]
X


sibsp      fare      age
0      0  211.3375  29.0000
1      1  151.5500   0.9167
2      1  151.5500   2.0000
3      1  151.5500  30.0000
4      1  151.5500  25.0000
5      0   26.5500  48.0000

In [ ]:
from sklearn.experimental import enable_iterative_imputer
#enable_iterative_imputer. This line is necessary because IterativeImputer is part of the experimental module in scikit-learn.
from sklearn.impute import IterativeImputer
impute=IterativeImputer()
impute.fit_transform(X)

array([[  0.    , 211.3375,  29.    ],
       [  1.    , 151.55  ,   0.9167],
       [  1.    , 151.55  ,   2.    ],
       [  1.    , 151.55  ,  30.    ],
       [  1.    , 151.55  ,  25.    ],
       [  0.    ,  26.55  ,  48.    ]])

In [ ]:
# KNN Imputer
from sklearn.impute import KNNImputer
imputr=KNNImputer(n_neighbors=2)
impute.fit_transform(X)

array([[  0.    , 211.3375,  29.    ],
       [  1.    , 151.55  ,   0.9167],
       [  1.    , 151.55  ,   2.    ],
       [  1.    , 151.55  ,  30.    ],
       [  1.    , 151.55  ,  25.    ],
       [  0.    ,  26.55  ,  48.    ]])

In [ ]:
#missingness in the model
import pandas as pd
import numpy as np

X =pd.DataFrame({'Age ': [20,30,20,np.nan,10]})
X


Age 
0  20.0
1  30.0
2  20.0
3   NaN
4  10.0

In [ ]:
from sklearn.impute import SimpleImputer
# impute the Mean
imputer=SimpleImputer()
imputer.fit_transform(X)

array([[20.],
       [30.],
       [20.],
       [20.],
       [10.]])

In [ ]:
imputer= SimpleImputer(add_indicator=True)
imputer.fit_transform(X)

array([[20.,  0.],
       [30.,  0.],
       [20.,  0.],
       [20.,  1.],
       [10.,  0.]])

In [ ]:
import missingno as msno
import pandas as pd
data =pd.read_csv('customer_churn.csv', nrows=100)
print(data.shape)
print(data)

(100, 10)
               Names   Age  Total_Purchase  Account_Manager  Years  Num_Sites  \
0   Cameron Williams  42.0        11066.80                0   7.22        8.0   
1      Kevin Mueller  41.0        11916.22                0   6.50       11.0   
2        Eric Lozano  38.0        12884.75                0   6.67       12.0   
3      Phillip White  42.0         8010.76                0   6.71       10.0   
4     Cynthia Norton  37.0         9191.58                0   5.56        9.0   
..               ...   ...             ...              ...    ...        ...   
95        Tammy Reed  49.0        13173.80                1   6.36       12.0   
96        Devin Cook  29.0         8688.17                1   5.70        9.0   
97   Joseph Mitchell  40.0        11434.61                1   8.51       10.0   
98    Brett Allen MD  45.0        12309.39                1   4.57       11.0   
99      Daniel Bates  30.0        10744.14                1   7.16        9.0   

           Onboar

In [ ]:

data.dropna()
data.shape

(100, 10)

In [ ]:
data.dropna(axis=1)

Names   Age  Total_Purchase  Account_Manager  Years  Num_Sites  \
0   Cameron Williams  42.0        11066.80                0   7.22        8.0   
1      Kevin Mueller  41.0        11916.22                0   6.50       11.0   
2        Eric Lozano  38.0        12884.75                0   6.67       12.0   
3      Phillip White  42.0         8010.76                0   6.71       10.0   
4     Cynthia Norton  37.0         9191.58                0   5.56        9.0   
..               ...   ...             ...              ...    ...        ...   
95        Tammy Reed  49.0        13173.80                1   6.36       12.0   
96        Devin Cook  29.0         8688.17                1   5.70        9.0   
97   Joseph Mitchell  40.0        11434.61                1   8.51       10.0   
98    Brett Allen MD  45.0        12309.39                1   4.57       11.0   
99      Daniel Bates  30.0        10744.14                1   7.16        9.0   

           Onboard_date                                           Location  \
0   2013-08-30 07:00:40      10265 Elizabeth Mission Barkerburgh, AK 89518   
1   2013-08-13 00:38:46  6157 Frank Gardens Suite 019 Carloshaven, RI 1...   
2   2016-06-29 06:20:07             1331 Keith Court Alyssahaven, DE 90114   
3   2014-04-22 12:43:12       13120 Daniel Mount Angelabury, WY 30645-4695   
4   2016-01-19 15:31:15                765 Tricia Row Karenshire, MH 71730   
..                  ...                                                ...   
95  2007-10-09 18:07:48  3067 Lindsay Road Apt. 683 Port Jonathan, NY 8...   
96  2015-02-05 11:35:45     237 Antonio Lock Lake Christianville, IN 42022   
97  2009-11-17 23:38:40         3422 Zhang View Estradabury, SC 66970-2923   
98  2008-02-07 15:42:36  03559 Rodriguez Prairie Apt. 826 Rachelfurt, N...   
99  2008-09-13 11:53:42        488 Lewis Village Crawfordborough, WY 43563   

                        Company  Churn  
0                    Harvey LLC      1  
1                    Wilson PLC      1  
2   Miller, Johnson and Wallace      1  
3                     Smith Inc      1  
4                    Love-Jones      1  
..                          ...    ...  
95                  Russo-Rivas      1  
96                  Fleming LLC      1  
97                      Lee LLC      1  
98                 Brown-Rangel      1  
99                     Hunt PLC      1  

[100 rows x 10 columns]

In [ ]:

#lets introduce 50% error in the dataframe

In [ ]:
import numpy as np
def intro(x,percentage):
    n=int(len(x)*(percentage -x.isna().mean()))
    idxs=np.random.choice(len(x),max(n,0),replace=False,p=x.notna()/x.notna().sum())
    x.iloc[idxs]=np.nan

In [ ]:
sample=data.apply(intro,percentage=.5)


In [ ]:
sample.head()

Names              None
Age                None
Total_Purchase     None
Account_Manager    None
Years              None
dtype: object

In [ ]:
# droping the row containg null in lolfrongtage

#data[data['LotFrontage'].notnull()]

In [ ]:
#data_app=data[(data['LotFrontage'].notnull()) & data['Alley'].notnull()]
#data_app.shape

In [ ]:
##data.shape

In [ ]:
#data_app=data[(data['LotFrontage'].notnull()) & data['Alley'].notnull()]
#data_app.shape

In [ ]:
#data['Alley'].fillna("Empty")